title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

github:
  about_url: ./index.html
  data_url: ./datasets.html
  tutorial_url: ./tutorial.html
  contribute_url: ./contribute.html
  contact_url: ./contact.html
