#!/bin/bash

# Rayleigh-Bénard Convection
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r0 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r1 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r2 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r3 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r4 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r5 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r6 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r7 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r8 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r9 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r0 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r1 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r2 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r3 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r4 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r5 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r6 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r7 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r8 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r9 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r0 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r1 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r2 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r3 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r4 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r5 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r6 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r7 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r8 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r9 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r0 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r1 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r2 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r3 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r4 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r5 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r6 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r7 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r8 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r0 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r1 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r2 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r3 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r4 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r5 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r6 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r7 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r8 --unzip
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r9 --unzip
