#!/bin/bash
kaggle datasets download -d waitongchung/blastnet-momentum-3d-sr-dataset
kaggle datasets download -d waitongchung/inert-ch4o2-hit-dns
kaggle datasets download -d waitongchung/forced-hit-ch4-air-ffcm
kaggle datasets download -d waitongchung/round-jet-premixed-bfer
kaggle datasets download -d waitongchung/round-jet-premixed-coffee
kaggle datasets download -d jguo96/transcritical-n2-channel-dns
kaggle datasets download -d waitongchung/premixed-flame-wall-ch4-air-dns-gri
kaggle datasets download -d waitongchung/full-lifted-flame-dns-li

kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-2
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-3
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-4
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-5
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-6
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-7
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-8
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-9
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-11
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-12
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-13
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-17
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-18
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-19
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-22
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-23
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-24
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-26
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-27
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-28
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-30
kaggle datasets download -d waitongchung/free-propagating-h2-vit-air-li-case-32

kaggle datasets download -d bassemakoush/canonical-hit-dns-00-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-00-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-01-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-01-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-02-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-02-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-03-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-03-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-04-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-04-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-05-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-05-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-06-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-06-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-07-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-07-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-08-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-08-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-09-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-09-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-10-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-10-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-11-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-11-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-12-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-12-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-13-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-13-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-14-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-14-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-15-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-15-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-16-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-16-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-17-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-17-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-18-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-18-pressure
kaggle datasets download -d bassemakoush/canonical-hit-dns-19-velocity
kaggle datasets download -d bassemakoush/canonical-hit-dns-19-pressure

kaggle datasets download -d victorcoulon/premixed-flame-nh3-h2-dns-1
kaggle datasets download -d victorcoulon/premixed-flame-nh3-h2-dns-2
kaggle datasets download -d victorcoulon/premixed-flame-nh3-h2-dns-3
kaggle datasets download -d victorcoulon/premixed-flame-nh3-h2-dns-4

kaggle datasets download -d sharmapushan/hydrogen-jet-8000
kaggle datasets download -d sharmapushan/hydrogen-jet-5000
kaggle datasets download -d sharmapushan/hydrogen-jet-7500
kaggle datasets download -d sharmapushan/hydrogen-jet-9000
kaggle datasets download -d sharmapushan/hydrogen-jet-10000
kaggle datasets download -d sharmapushan/hydrogen-jet-6000
kaggle datasets download -d sharmapushan/hydrogen-jet-11000
kaggle datasets download -d sharmapushan/hydrogen-jet-7000
kaggle datasets download -d sharmapushan/nonreacting-hydrogen-jet-5000
kaggle datasets download -d sharmapushan/nonreacting-hydrogen-jet-10000

kaggle datasets download -d bassemakoush/passive-fhit-dns-r0
kaggle datasets download -d bassemakoush/passive-fhit-dns-r1
kaggle datasets download -d bassemakoush/passive-fhit-dns-r2
kaggle datasets download -d bassemakoush/passive-fhit-dns-r3
kaggle datasets download -d bassemakoush/passive-fhit-dns-r4

kaggle datasets download -d blastnet/firebench-u10-2
kaggle datasets download -d blastnet/firebench-u10-3
kaggle datasets download -d blastnet/firebench-u10-9
kaggle datasets download -d blastnet/firebench-u10-4
kaggle datasets download -d blastnet/firebench-u10-5
kaggle datasets download -d blastnet/firebench-u10-6
kaggle datasets download -d blastnet/firebench-u10-7
kaggle datasets download -d blastnet/firebench-u10-8
kaggle datasets download -d blastnet/firebench-u10-10
kaggle datasets download -d blastnet/h2ch4-jet-h10-5
kaggle datasets download -d blastnet/h2ch4-jet-h10-2
kaggle datasets download -d blastnet/h2ch4-jet-h10-3
kaggle datasets download -d blastnet/h2ch4-jet-h50-3
kaggle datasets download -d blastnet/h2ch4-jet-h50-4
kaggle datasets download -d blastnet/h2ch4-jet-h0-4
kaggle datasets download -d blastnet/h2ch4-jet-h0-2
kaggle datasets download -d blastnet/h2ch4-jet-h80-3
kaggle datasets download -d blastnet/h2ch4-jet-h80-5
kaggle datasets download -d blastnet/h2ch4-jet-h50-1
kaggle datasets download -d blastnet/h2ch4-jet-h0-1
kaggle datasets download -d blastnet/h2ch4-jet-h10-1
kaggle datasets download -d blastnet/h2ch4-jet-h80-1
kaggle datasets download -d blastnet/h2ch4-jet-h50-2
kaggle datasets download -d blastnet/h2ch4-jet-h0-3
kaggle datasets download -d blastnet/h2ch4-jet-h10-4
kaggle datasets download -d blastnet/h2ch4-jet-h80-2
kaggle datasets download -d blastnet/h2ch4-jet-h0-5
kaggle datasets download -d blastnet/h2ch4-jet-h50-5
kaggle datasets download -d blastnet/h2ch4-jet-h80-4

kaggle datasets download -d blastnet/canonical-rbc-dns-c0r0
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r1
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r2
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r3
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r4
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r5
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r6
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r7
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r8
kaggle datasets download -d blastnet/canonical-rbc-dns-c0r9
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r0
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r1
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r2
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r3
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r4
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r5
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r6
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r7
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r8
kaggle datasets download -d blastnet/canonical-rbc-dns-c1r9
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r0
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r1
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r2
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r3
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r4
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r5
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r6
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r7
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r8
kaggle datasets download -d blastnet/canonical-rbc-dns-c2r9
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r0
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r1
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r2
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r3
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r4
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r5
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r6
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r7
kaggle datasets download -d blastnet/canonical-rbc-dns-c3r8
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r0
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r1
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r2
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r3
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r4
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r5
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r6
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r7
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r8
kaggle datasets download -d blastnet/canonical-rbc-dns-c4r9

kaggle datasets download -d blastnet/premixed-flame-slot-burner-dns-h2air-phi035
kaggle datasets download -d blastnet/premixed-flame-slot-burner-dns-h2air-phi04
kaggle datasets download -d blastnet/premixed-flame-slot-burner-dns-h2air-phi05
kaggle datasets download -d blastnet/premixed-flame-slot-burner-dns-h2air-phi06
kaggle datasets download -d blastnet/premixed-flame-slot-burner-dns-h2air-phi07

# Pk Yeung
kaggle datasets download -d blastnet/forcedhit-dns-re390-vp
kaggle datasets download -d blastnet/forcedhit-dns-re390-scalar

kaggle datasets download -d blastnet/forcedhit-dns-re650-p1
kaggle datasets download -d blastnet/forcedhit-dns-re650-p2
kaggle datasets download -d blastnet/forcedhit-dns-re650-u1
kaggle datasets download -d blastnet/forcedhit-dns-re650-u2
kaggle datasets download -d blastnet/forcedhit-dns-re650-v1
kaggle datasets download -d blastnet/forcedhit-dns-re650-v2
kaggle datasets download -d blastnet/forcedhit-dns-re650-w1
kaggle datasets download -d blastnet/forcedhit-dns-re650-w2
kaggle datasets download -d blastnet/forcedhit-dns-re650-y11
kaggle datasets download -d blastnet/forcedhit-dns-re650-y12
kaggle datasets download -d blastnet/forcedhit-dns-re650-y21
kaggle datasets download -d blastnet/forcedhit-dns-re650-y22
kaggle datasets download -d blastnet/forcedhit-dns-re650-y31
kaggle datasets download -d blastnet/forcedhit-dns-re650-y32

# Channel Flow DNS datasets (seq and eq variants)
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p000-020
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p021-041
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p042-062
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p063-083
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p084-104
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p105-125
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p126-146
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p147-167
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p168-188
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p189-209
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p210-230
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p231-251
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p252-272
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p273-293
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p294-314
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p315-335
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p336-356
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p357-377
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p378-398
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p399-419
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p420-440
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p441-461
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p462-482
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p483-503
kaggle datasets download -d blastnet/channelflow-dns-Re544-eq-p504-509

kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p000-020
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p021-041
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p042-062
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p063-083
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p084-104
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p105-125
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p126-146
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p147-167
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p168-188
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p189-209
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p210-230
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p231-251
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p252-272
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p273-293
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p294-314
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p315-335
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p336-356
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p357-377
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p378-398
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p399-419
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p420-440
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p441-461
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p462-482
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p483-503
kaggle datasets download -d blastnet/channelflow-dns-Re544-seq-p504-509